In [43]:
import torch

#### (一) Tensor定义: torch.xxxx

In [44]:
# 不同类型的Tensor定义，其中Tensor默认为FloatTensor()
a = torch.IntTensor([5,5,5])
b = torch.FloatTensor([1,1,1])
c = torch.CharTensor([1,1,1])
d = torch.LongTensor([1,1,1])
e = torch.ShortTensor([1,1,1])

# 输出
for i, v in enumerate([a,b,c,d,e]):
    print(v)

tensor([5, 5, 5], dtype=torch.int32)
tensor([1., 1., 1.])
tensor([1, 1, 1], dtype=torch.int8)
tensor([1, 1, 1])
tensor([1, 1, 1], dtype=torch.int16)


In [8]:
# 使用其他形式的数值对Tensor进行赋值
# 使用数组
# 使用列表
# 使用元组
# 使用XX

tensor([5, 5, 5], dtype=torch.int32)
tensor([1., 1., 1.])
tensor([1, 1, 1], dtype=torch.int8)
tensor([1, 1, 1])
tensor([1, 1, 1], dtype=torch.int16)


#### （二）Tensor属性: 变量.xxx

In [10]:
# 属性shape
for i, v in enumerate([a,b,c,d,e]):
    print(i,'属性:',v.shape)

# 属性dtype
for i, v in enumerate([a,b,c,d,e]):
    print(i,'属性:',v.dtype)

# 属性device
for i, v in enumerate([a,b,c,d,e]):
    print(i,'属性:',v.device)

0 属性: torch.Size([3])
1 属性: torch.Size([3])
2 属性: torch.Size([3])
3 属性: torch.Size([3])
4 属性: torch.Size([3])
0 属性: torch.int32
1 属性: torch.float32
2 属性: torch.int8
3 属性: torch.int64
4 属性: torch.int16
0 属性: cpu
1 属性: cpu
2 属性: cpu
3 属性: cpu
4 属性: cpu


#### （三）Tensor运算:torch.XXX

In [42]:
import numpy as np
T1 = torch.ones(5,5)
T2 = torch.IntTensor(np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12])))
print('原始矩阵\n',T2)

# 切片索引
T2[:2,:2] = 999
print('切片索引+999修改展示\n',T2)

# 张量连接
a = torch.zeros(5,5,)
b = torch.ones(5,5,)
T3 = torch.cat([a,b], dim=1)
print('张量连接\n',T3)

# 张量倍增
T4 = torch.mul(a,b)
T5 = a * b
print('torch.mul:\n',T4,'\n直接相乘:\n',T5)

# 其他形式:使用_
# 加数: .add_()
T6 = T2.add_(100)
print(T6)
# 复制: .copy_()
T7 = T2.copy_(T2)
print(T7)
# 转职: .t_()
T8 = T2.t_()
print(T8)

原始矩阵
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)
切片索引+999修改展示
 tensor([[999, 999,   3],
        [999, 999,   6],
        [  7,   8,   9],
        [ 10,  11,  12]], dtype=torch.int32)
张量连接
 tensor([[0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])
torch.mul:
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 
直接相乘:
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1099, 1099,  103],
        [1099, 1099,  106],
        [ 107,  108,  109],
        [ 110,  111,  112]], dtype=torch.int32)
tensor([[1099, 1099,  103],
        [1099